// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBijzcgen_31bMDv8XZM_lxd6xL_Qf2GbQ',
    appId: '1:603627274130:web:b1112cf8853c38fbc94b4b',
    messagingSenderId: '603627274130',
    projectId: 'shestyleproject',
    authDomain: 'shestyleproject.firebaseapp.com',
    storageBucket: 'shestyleproject.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRXvV8IXNsojF5pF6na1itzZ5WHbatTpU',
    appId: '1:603627274130:android:31f195b090cda518c94b4b',
    messagingSenderId: '603627274130',
    projectId: 'shestyleproject',
    storageBucket: 'shestyleproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsEmA-MFXg1151Tr8BguvBJEPhYJKzAkQ',
    appId: '1:603627274130:ios:1876b41359e86239c94b4b',
    messagingSenderId: '603627274130',
    projectId: 'shestyleproject',
    storageBucket: 'shestyleproject.firebasestorage.app',
    iosClientId: '603627274130-hdifb396cr3u4tm3k0sjge4naj3c87n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsEmA-MFXg1151Tr8BguvBJEPhYJKzAkQ',
    appId: '1:603627274130:ios:1876b41359e86239c94b4b',
    messagingSenderId: '603627274130',
    projectId: 'shestyleproject',
    storageBucket: 'shestyleproject.firebasestorage.app',
    iosClientId: '603627274130-hdifb396cr3u4tm3k0sjge4naj3c87n8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBijzcgen_31bMDv8XZM_lxd6xL_Qf2GbQ',
    appId: '1:603627274130:web:6ae1257c32c122d6c94b4b',
    messagingSenderId: '603627274130',
    projectId: 'shestyleproject',
    authDomain: 'shestyleproject.firebaseapp.com',
    storageBucket: 'shestyleproject.firebasestorage.app',
  );
}
